teachersupport/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.studentlogin, name='studentlogin'),
    url(r'^proflogin/$', views.proflogin, name='proflogin'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^form/$', views.form, name='form'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^requestofficehours/$', views.requestofficehours,
        name='requestofficehours'),
    url(r'^respondtorequests/$', views.respondtorequests, name='respondtorequests')
    # url(r'^booksuppoty/$', views.bookSupport, name='booksupport')
]

webApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^teachersupport/', include('teachersupport.urls', namespace='teachersupport'))
]

teachersupport/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Student(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=12)
    logged_in = models.BooleanField(default=False)
    type = models.CharField(max_length=100)

    def __str__(self):
        return self.email


class Professor(Student):

    def __str__(self):
        """Unicode representation of Course."""
        return self.name


class OfficeHours(models.Model):
    student_id = models.CharField(max_length=100)
    #student_name = models.CharField(max_length=100)
    professor_needed = models.CharField(max_length=100)
    professor = models.ForeignKey(Professor)


class TimeSet(models.Model):
    date_set = models.DateField()
    time_set = models.TimeField()
    professor = models.ForeignKey(Professor)

    def __str__(self):
        """Unicode representation of Response."""
        pass


class Slot(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        """Unicode representation of Course."""
        return self.title


class Course(models.Model):
    """Model definition for Course."""
    name = models.CharField(max_length=100)

    # TODO: Define fields here

    class Meta:
        """Meta definition for Course."""

        verbose_name = 'Course'
        verbose_name_plural = 'Courses'

    def __str__(self):
        """Unicode representation of Course."""
        return self.name


class Day(models.Model):
    """Model definition for Day."""
    name = models.CharField(max_length=100)

    class Meta:
        """Meta definition for Day."""

        verbose_name = 'Day'
        verbose_name_plural = 'Days'

    def __str__(self):
        """Unicode representation of Day."""
        return self.name


class Table(models.Model):
    """Model definition for Table."""
    Day = models.ForeignKey(Day, on_delete=models.CASCADE, related_name='day')
    Slot = models.ForeignKey(
        Slot, on_delete=models.CASCADE, related_name='slot')
    Course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name='course')
    # TODO: Define fields here

    class Meta:
        """Meta definition for Table."""
        unique_together = (('Day', 'Slot', 'Course'),)
        verbose_name = 'Table'
        verbose_name_plural = 'Tables'

    def __str__(self):
        return self.Day.name+","+self.Slot.title

teachersupport/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.urls import reverse

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from models import *

# Create your views here.


def checkAuth(request):
    try:
        m = request.session['member_id']
    except:
        return 0
    return m


def index(request):
    logged_in = checkAuth(request)
    return render(request, "index.html", context={'log': logged_in})


def dashboard(request):
    logged_in = checkAuth(request)
    return render(request, "dashboard.html", context={'log': logged_in})


def form(request):
    return render(request, 'form.html')


def studentlogin(request):
    name = request.POST['email']
    pwd = request.POST['password']
    context = {}
    try:
        usr = Student.objects.get(email=name)
    except (KeyError, Student.DoesNotExist):
        context['errors'] = True
        return render(request, "form.html", context)
    else:
        if (usr.password == pwd):
            if usr.type != "Student":
                return HttpResponseRedirect(reverse('teachersupport:form'))
            else:
                usr.logged_in = True
                usr.save()
                request.session['member_id'] = usr.id
                request.session['logged_type'] = usr.type
                prof_response = TimeSet.objects.all()
                # all_responses = []
                # for obj in prof_response:
                #     temp_d = {}
                #     temp_d[obj.professor.id] = {
                #         'name': obj.professor.name, 'date_set': obj.date_set, 'time_set': obj.date.set}
                #     all_responses.append(temp_d)

                profs = []
                professors = Professor.objects.all()
                for i in range(0, len(professors)):
                    profs.append(professors[i].name)
                request.session['professors'] = profs
                # request.session['prof_responses'] = all_responses

                request.session.set_expiry(0)
                return HttpResponseRedirect(reverse('teachersupport:dashboard'))
        else:
            return render(request, "form.html", context)


def proflogin(request):
    name = request.POST['email']
    pwd = request.POST['password']
    context = {}
    try:
        usr = Professor.objects.get(email=name)
    except (KeyError, Professor.DoesNotExist):
        context['errors'] = True
        return render(request, "form.html", context)
    else:
        if (usr.password == pwd):
            if usr.type != "Professor":
                return render(request, "form.html", context)
            else:
                usr.logged_in = True
                usr.save()
                officehourrequests = OfficeHours.objects.all()
                students = {}
                all_students = Student.objects.all()
                for i in range(0, len(all_students)):
                    students[all_students[i].id] = all_students[i].id
                request.session['students'] = students
                requests = {}
                requests[usr.id] = []
                for i in officehourrequests:
                    if i.professor.id == usr.id:
                        requests[usr.id].append(i.student_id)

                students_in_need = []
                for i in requests:
                    for j in requests[i]:
                        std_obj_id = Student.objects.get(id=j).id
                        std_obj_name = Student.objects.get(id=j).name
                        std_request = {}
                        std_request[std_obj_id] = std_obj_name
                        if any(std_obj_id in d for d in students_in_need) == False:
                            students_in_need.append((std_obj_id, std_obj_name))
                        else:
                            pass
                request.session['member_id'] = usr.id
                request.session['logged_type'] = usr.type
                request.session['officehour_requests'] = requests
                request.session['students_in_need'] = students_in_need
                request.session.set_expiry(0)
                return HttpResponseRedirect(reverse('teachersupport:dashboard'))
        else:
            return render(request, "form.html", context)


def logout(request):
    if request.session['member_id'] == '':
        return render(request, "form.html", context)
    else:

        try:
            m_id = request.session['member_id']
        except KeyError:
            pass
        else:
            m = Student.objects.get(pk=m_id) or Professor.objects.get(pk=m_id)
            m.logged_in = False
            m.save()
            del request.session['member_id']
            return render(request, "index.html")


def requestofficehours(request):
    student_id = request.POST.get('student', '')
    professor_needed = request.POST.get('professor', '')
    student_name = Student.objects.get(id=student_id).name
    try:
        usr = Professor.objects.get(name=professor_needed)
        usr_id = usr.id
    except (KeyError, Professor.DoesNotExist):
        context['errors'] = True
        return render(request, "dashboard.html", context)
    else:
        officeHour = OfficeHours.objects.create(
            student_id=student_id, professor_needed=professor_needed, professor=usr
        )
        return HttpResponseRedirect(reverse('teachersupport:dashboard'))


def respondtorequests(request):
    date_set = request.POST.get('date', '')
    time_set = request.POST.get('time', '')
    professor = Professor.objects.get(id=request.session['member_id'])
    professor_id = professor.id

    prof_response = TimeSet.objects.create(
        date_set=date_set, time_set=time_set, professor=professor)
    return HttpResponseRedirect(reverse('teachersupport:dashboard'))


def signup(request):
    name = request.POST.get('name', '')
    mail = request.POST.get('email', '')
    password = request.POST.get('passwordsignup', '')
    pwd2 = request.POST.get('passwordsignup_confirm', '')
    accountType = request.POST.get('account_type', '')
    context = {}

    if (password != pwd2):
        context['wrong'] = True
        return render(request, "form.html", context)
    else:
        if accountType == 'Student':
            studentMember = Student.objects.create(
                name=name, email=mail, password=password, logged_in=True)
        else:
            profMember = Professor.objects.create(
                name=name, email=mail, password=password, available_time=time_available, logged_in=True
            )

        return HttpResponseRedirect(reverse('teachersupport:index'))

    return HttpResponse("signup")

teachersupport/templates/base.html
{% load static %}

<head>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.2.7/css/select.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">

    <script type="text/javascript" src="{% static 'js/template.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/template.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Viga" rel="stylesheet">
    <title>UPC User Platform</title>

</head>

<body>
    <header role="banner">
        <div id="cd-logo"><a href="/teachersupport/"><img src="{% static 'img/upc.png' %}" alt="Logo" style="width:50px;height:50px;"></a></div>

        <nav class=" main-nav ">
            <ul>
                {% if not log %}
                <li><a class="cd-signin " href="{% url 'teachersupport:form'%} ">Sign in/Register</a></li>

                {% else %}
                <li><a class="cd-signin " href="{% url 'teachersupport:logout'%} ">Logout</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block body %} {% endblock %}
</body>

teachersupport/templates/dashboard.html
{% extends 'base.html'%} {% load static %} {% block body %}

<div class="container">
    <div class="row">
        <div class="col-sm">
            {% if request.session.logged_type == "Student" %}
            <button type="button" class="btn btn-primary loginbutton" data-toggle="modal" data-target="#officeHoursModal">
                Request Office Hours
            </button>

            <button type="button" class="btn btn-primary signupbutton" data-toggle="modal" data-target="#viewModal">
                View Responses
            </button>

            <div class="modal" id="officeHoursModal" tabindex="-1" role="dialog" aria-labelledby="officeHoursModal" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Request Office Hours</h4>
                        </div>
                        <div class="modal-body">
                            <form action="/teachersupport/requestofficehours/" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="prof">Professor</label>
                                    <select name="professor">
                                        {% for item in request.session.professors %}
                                        <h4>
                                            <option value="{{item}}">{{item}}</option>
                                        </h4>
                                        {% endfor %}
                                    </select>
                                    <input type="hidden" value="{{request.session.member_id}}" name="student">
                                </div>

                                <br/>

                                <button type="submit" class="btn btn-primary">Request</button>
                            </form>


                        </div>
                        <div class="modal-footer">
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal" id="viewModal" tabindex="-1" role="dialog" aria-labelledby="viewModalTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">View Responses</h4>
                        </div>
                        <div class="modal-body">
                            <form>
                                {% csrf_token %}
                                <div class="form-group">
                                    {% for student in request.session.all_responses %}
                                    <label>{{student}}</label>
                                    {% endfor %}

                                </div>

                                <br/>

                                <button type="submit" class="btn btn-primary">Dismiss</button>
                            </form>


                        </div>
                        <div class="modal-footer">
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
            <button type="button" class="btn btn-primary loginbutton" data-toggle="modal" data-target="#profModal">
                View Student Requests
            </button>

            <button type="button" class="btn btn-primary signupbutton" data-toggle="modal" data-target="#respond">
                Respond To Student Requests
            </button>

            <div class="modal" id="profModal" tabindex="-1" role="dialog" aria-labelledby="profModalTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">View Requests</h4>
                        </div>
                        <div class="modal-body">
                            <form>
                                {% csrf_token %}
                                <div class="form-group">
                                    {% for student in request.session.students_in_need %}
                                    <label>{{student}}</label>
                                    {% endfor %}

                                </div>

                                <br/>

                                <button type="submit" class="btn btn-primary">Dismiss</button>
                            </form>


                        </div>
                        <div class="modal-footer">
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal" id="respond" tabindex="-1" role="dialog" aria-labelledby="respondTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Set Time</h4>
                        </div>
                        <div class="modal-body">
                            <form action="/teachersupport/respondtorequests/" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="date">Date</label>
                                    <input type="date" name="date">

                                </div>
                                <div class="form-group">
                                    <label for="time">Time</label>
                                    <input type="time" name="time" min="9:00" max="16:00" required>

                                </div>

                                <br/>

                                <button type="submit" class="btn btn-primary">Set TIme</button>
                            </form>


                        </div>
                        <div class="modal-footer">
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>


            {% endblock %}
        </div>

teachersupport/templates/form.html
{% extends 'base.html'%} {% load static %} {% block body %}

<div class="container">
    <div class="row">
        <div class="col-sm">
            <button type="button" class="btn btn-primary loginbutton" data-toggle="modal" data-target="#studentModal">
                Student Login
            </button>
            <button type="button" class="btn btn-primary signupbutton" data-toggle="modal" data-target="#profModal">
                Professor Login
            </button>
        </div>
    </div>
    <div class="modal" id="studentModal" tabindex="-1" role="dialog" aria-labelledby="studentModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Login</h4>
                </div>
                <div class="modal-body">
                    <form action="/teachersupport/login/" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter E-mail address">
                        </div>
                        <div class="form-group">
                            <label for="description">Password</label>
                            <input type="password" name="password" class="form-control" id="password" placeholder="Enter Password">
                        </div>

                        <br/>

                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>


                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
    <div class="modal" id="profModal" tabindex="-1" role="dialog" aria-labelledby="profModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Login</h4>
                </div>
                <div class="modal-body">
                    <form action="/teachersupport/proflogin/" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter E-mail address">
                        </div>
                        <div class="form-group">
                            <label for="description">Password</label>
                            <input type="password" name="password" class="form-control" id="password" placeholder="Enter Password">
                        </div>

                        <br/>

                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>


                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
</div>




{% comment %}
<div class="container ">

    <header style="padding-top: 100px; ">
        {% if errors %}
        <h1>Invalid Username/Password</h1>
        {% endif %} {% if wrong %}
        <h1>Invalid Username/Password</h1>
        {% endif %}
    </header>
    <section>
        <div id="container_demo ">
            <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
            <a class="hiddenanchor " id="toregister "></a>
            <a class="hiddenanchor " id="tologin "></a>
            <div id="wrapper ">
                <div id="login " class="animate form ">
                    <form action="{% url 'teachersupport:login'%} " autocomplete="on " method="POST ">
                        {% csrf_token %}
                        <h1>Log in</h1>
                        <p>
                            <label for="email " class="email " data-icon="u "> Your E-mail </label>
                            <input id="email " name="email " required="required " type="email
    " placeholder="mymail@me.com " />
                        </p>
                        <p>
                            <label for="password " class="youpasswd " data-icon="p "> Your password </label>
                            <input id="password " name="password " required="required " type="password
    " placeholder="eg. X8df!90EO " />
                        </p>
                        <p class="keeplogin ">
                            <input type="checkbox " name="loginkeeping " id="loginkeeping " value="loginkeeping " />
                            <label for="loginkeeping ">Keep me logged in</label>
                        </p>
                        <p class="login button ">
                            <input type="submit " value="Login " />
                        </p>
                        <p class="change_link ">
                            Not a member yet ?
                            <a href="#toregister " class="to_register ">Join us</a>
                        </p>
                    </form>
                </div>

                <div id="register " class="animate form ">
                    <form action="{% url 'teachersupport:signup'%} " autocomplete="on " method="POST
    " enctype="multipart/form-data ">
                        {% csrf_token %}
                        <h1> Sign up </h1>
                        <p>
                            <label for="name " class="uname " data-icon="u ">Name</label>
                            <input id="name " name="name " required="required " type="text
    " placeholder="John Doe " />
                        </p>
                        <p>
                            <label for="email " class="youmail " data-icon="e ">E-Mail</label>
                            <input id="email " name="email " required="required " type="email
    " placeholder="mysupermail@mail.com " />
                        </p>
                        <p>
                            <label for="passwordsignup " class="youpasswd " data-icon="p ">Your password </label>
                            <input id="passwordsignup " name="passwordsignup " required="required " type="password
    " placeholder="eg. X8df!90EO " />
                        </p>
                        <p>
                            <label for="passwordsignup_confirm " class="youpasswd " data-icon="p ">Please confirm your password
                            </label>
                            <input id="passwordsignup_confirm " name="passwordsignup_confirm " required="required
    " type="password " placeholder="eg. X8df!90EO " />
                        </p>
                        <p>
                            <label for="img " class="youpasswd " data-icon="i ">Upload your img </label>
                            <input id="img " name="img " required="required " type="file " placeholder=".... " />
                        </p>
                        <p class="signin button ">
                            <input type="submit " value="Sign up " />
                        </p>
                        <p class="change_link ">
                            Already a member ?
                            <a href="#tologin " class="to_register "> Go and log in </a>
                        </p>
                    </form>
                </div>

            </div>
        </div>
    </section>
</div> {% endcomment %} {% endblock %}

teachersupport/templates/index.html
{% extends 'base.html' %} {% load static %} {% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm">
            <img class="body-img" src="{% static 'img/body.png' %}" alt="UPC">
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <h2>UPC User Platform</h2>
        </div>
    </div>
</div>
{% endblock %}

teachersupport/templates/schedule.html
{% extends 'base.html' %} {% load static %} {% block body %}
<div class="container">
    <div class="row">
        <div class="col-sm">
            <table id="example" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>Day</th>
                        <th>First</th>
                        <th>Second</th>
                        <th>Third</th>
                        <th>Fourth</th>
                        <th>Fifth</th>
                        <th>Sixth</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Sunday</td>
                        <td>a</td>
                        <td>b</td>
                        <td>c</td>
                        <td>d</td>
                        <td>e</td>
                        <td>e</td>
                    </tr>
                    <tr>
                        <td>Monday</td>
                        <td>f</td>
                        <td>g</td>
                        <td>h</td>
                        <td>i</td>
                        <td>j</td>
                        <td>e</td>
                    </tr>
                    <tr>
                        <td>Tuesday</td>
                        <td>k</td>
                        <td>k</td>
                        <td>k</td>
                        <td>k</td>
                        <td>k</td>
                        <td>e</td>
                    </tr>
                    <tr>
                        <td>Wednesday</td>
                        <td>k</td>
                        <td>k</td>
                        <td>k</td>
                        <td>k</td>
                        <td>k</td>
                        <td>e</td>
                    </tr>
                    <tr>
                        <td>Thursday</td>
                        <td>k</td>
                        <td>k</td>
                        <td>k</td>
                        <td>k</td>
                        <td>k</td>
                        <td>e</td>
                    </tr>
                    <tfoot></tfoot>
            </table>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#example').DataTable({
            "columnDefs": [
                { "orderable": false, "targets": 0 }
            ]
        });
    });
</script> {% endblock %}